repos:
  - repo: local
    hooks:
      - id: ruff check
        name: ruff check
        entry:  python3 -m ruff check . --preview
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff format
        name: ruff format
        entry:  python3 -m ruff format .
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: python3 -m mypy smurfdb/smurfdb.py smurfdb/test/test_smurfdb.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: tests
        entry: python3 -m pytest smurfdb/test/
        language: system
        always_run: true
        pass_filenames: false
