name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-2004:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install ubuntu dependencies
        run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y openssl
      - name: generate cert
        run: mkdir .lib && openssl req -newkey rsa:4096 -nodes -keyout .lib/selfsigned.key -x509 -days 36500 -out .lib/selfsigned.cert -subj "/C=US/ST=NRW/L=Earth/O=CompanyName/OU=IT/CN=localhost/emailAddress=email@example.com"
      - name: Test with pytest
        run: python -m pytest lotordb/test

  build-latest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install ubuntu dependencies
        run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y openssl
      - name: generate cert
        run: mkdir .lib && openssl req -newkey rsa:4096 -nodes -keyout .lib/selfsigned.key -x509 -days 36500 -out .lib/selfsigned.cert -subj "/C=US/ST=NRW/L=Earth/O=CompanyName/OU=IT/CN=localhost/emailAddress=email@example.com"
      - name: Test with pytest
        run: python -m pytest lotordb/test
